Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-03, with the labels that each got.

#228 Allow different layouts for RS units
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/utils/_typing.py
  coreblocks/utils/utils.py
Labels: microarch

#209 Configurable FU used by `GenParams`
  constants/ecp5_platforms.py
  coreblocks/core.py
  coreblocks/frontend/decoder.py
  coreblocks/fu/alu.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/mul_unit.py
  coreblocks/fu/unsigned_multiplication/common.py
  coreblocks/fu/unsigned_multiplication/fast_recursive.py
  coreblocks/fu/unsigned_multiplication/sequence.py
  coreblocks/fu/zbs.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/__init__.py
  coreblocks/params/fu_params.py
  coreblocks/params/genparams.py
  coreblocks/params/isa.py
  coreblocks/params/keys.py
  coreblocks/params/layouts.py
  coreblocks/params/mul_params.py
  coreblocks/params/optypes.py
  coreblocks/scheduler/scheduler.py
  coreblocks/stages/func_blocks_unifier.py
  coreblocks/stages/rs_func_block.py
  coreblocks/structs_common/rs.py
  coreblocks/utils/protocols.py
  scripts/synthesize
  test/common.py
  test/frontend/test_decode.py
  test/frontend/test_decoder.py
  test/frontend/test_fetch.py
  test/fu/functional_common.py
  test/fu/test_alu.py
  test/fu/test_jb_unit.py
  test/fu/test_mul_unit.py
  test/fu/test_unsigned_mul_unit.py
  test/fu/test_zbs.py
  test/lsu/test_dummylsu.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/stages/test_retirement.py
  test/structs_common/test_reorder_buffer.py
  test/structs_common/test_rs.py
  test/test_core.py
Labels: nice to have

#245 Fix the core_graph script after merging #209, and other cleanups
  constants/ecp5_platforms.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  scripts/core_graph
  scripts/synthesize
  test/common.py
  test/fu/test_mul_unit.py
  test/test_core.py
Labels: bug

#241 Make Sphinx CI fail on errors and warnings
  ci/build-docs.sh
  scripts/build-docs.sh
Labels: infrastructure

#249 Move from Docker Hub to GitHub Container Registry
  .github/workflows/benchmark.yml
Labels: infrastructure

#217 Zicsr extension - Unit and Register
  coreblocks/frontend/decode.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/structs_common/csr.py
  test/scheduler/test_rs_selection.py
  test/structs_common/test_csr.py
Labels: enhancement, microarch

#255 Add comments to `Priority` enum
  coreblocks/transactions/core.py
Labels: documentation

#246 ZBA extension built into ALU
  coreblocks/frontend/decoder.py
  coreblocks/fu/alu.py
  coreblocks/params/isa.py
  coreblocks/params/optypes.py
  test/fu/test_alu.py
Labels: enhancement

#248 Add a script exporting the core to Verilog
  coreblocks/transactions/core.py
  coreblocks/transactions/lib.py
  coreblocks/utils/_typing.py
  coreblocks/utils/debug_signals.py
  coreblocks/utils/utils.py
  scripts/gen_verilog.py
  test/common.py
  test/gtkw_extension.py
Labels: infrastructure

#189 TestbenchIO: new syntax suggestion for calls
  test/common.py
  test/frontend/test_decode.py
  test/frontend/test_fetch.py
  test/lsu/test_dummylsu.py
  test/peripherals/test_wishbone.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/structs_common/test_csr.py
  test/structs_common/test_reorder_buffer.py
  test/structs_common/test_rs.py
  test/test_core.py
  test/transactions/test_adapter.py
  test/transactions/test_methods.py
  test/transactions/test_transaction_lib.py
  test/transactions/test_transactions.py
  test/utils/test_fifo.py
Labels: tests, refactor

#259 Enums enums enums
  coreblocks/params/isa.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
Labels: enhancement

#244 Added overview of publications about exceptions
  docs/index.md
  docs/miscellany/exceptionsSummary.md
Labels: documentation, enhancement

#239 Stubs for amaranth.lib.data
  coreblocks/utils/_typing.py
  stubs/amaranth/hdl/ast.pyi
  stubs/amaranth/lib/data.pyi
Labels: enhancement

#240 Support amaranth.lib.data structures in assign
  coreblocks/utils/utils.py
  stubs/amaranth/hdl/ast.pyi
  test/transactions/test_assign.py
Labels: enhancement

#251 Wishbone connected to pins for synthesis benchmark
  constants/ecp5_pinout.py
  constants/ecp5_platforms.py
  scripts/synthesize.py
Labels: infrastructure, refactor

#256 Abstract away implementation of Wishbone master
  coreblocks/core.py
  coreblocks/params/genparams.py
  coreblocks/peripherals/wishbone.py
  scripts/gen_verilog.py
  scripts/synthesize.py
  test/test_core.py
Labels: refactor

#270 Replace setattr on m.submodules by indexing
  coreblocks/stages/rs_func_block.py
  coreblocks/transactions/lib.py
  test/stages/test_backend.py
  test/structs_common/test_rs.py
  test/transactions/test_transaction_lib.py
Labels: refactor

#263 New syntax for method mocks
  coreblocks/transactions/_utils.py
  coreblocks/transactions/core.py
  test/common.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/stages/test_retirement.py
  test/transactions/test_transaction_lib.py
Labels: transactions, refactor
