Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-07, with the labels that each got.

#343 "C" Standard Extension for Compressed Instructions
  coreblocks/core.py
  coreblocks/frontend/decode.py
  coreblocks/frontend/decoder.py
  coreblocks/frontend/fetch.py
  coreblocks/frontend/rvc.py
  coreblocks/fu/jumpbranch.py
  coreblocks/params/__init__.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/params/instr.py
  coreblocks/params/isa.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/utils/fifo.py
  test/common.py
  test/external/embench/board_config/coreblocks-sim/board.cfg
  test/external/riscv-tests/Makefile
  test/frontend/test_fetch.py
  test/frontend/test_rvc.py
  test/params/test_configurations.py
Labels: enhancement, review needed

#389 Division unit
  coreblocks/fu/div_unit.py
  coreblocks/fu/division/common.py
  coreblocks/fu/division/long_division.py
  coreblocks/params/configurations.py
  coreblocks/params/layouts.py
  scripts/run_tests.py
  test/fu/test_div_unit.py
  test/params/test_configurations.py
Labels: enhancement

#394 Exceptions implementation
  coreblocks/frontend/decode.py
  coreblocks/frontend/decoder.py
  coreblocks/frontend/fetch.py
  coreblocks/fu/jumpbranch.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/structs_common/csr.py
  coreblocks/utils/utils.py
  test/frontend/test_decode.py
  test/frontend/test_fetch.py
  test/fu/functional_common.py
  test/fu/test_jb_unit.py
  test/lsu/test_dummylsu.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/structs_common/test_csr.py
Labels: enhancement, microarch

#423 Remove wiki deploy
  .github/workflows/deploy_wiki.yml
Labels: infrastructure

#427 Simplified DummyLSU
  coreblocks/lsu/dummyLsu.py
Labels: refactor

#425 Single caller method check
  coreblocks/transactions/core.py
  test/transactions/test_transaction_lib.py
  test/transactions/test_transactions.py
Labels: transactions

#433 Improve GenericFunctionalTestUnit
  test/fu/functional_common.py
  test/fu/test_alu.py
  test/fu/test_div_unit.py
  test/fu/test_exception_unit.py
  test/fu/test_jb_unit.py
  test/fu/test_mul_unit.py
  test/fu/test_shift_unit.py
  test/fu/test_zbc.py
  test/fu/test_zbs.py
Labels: tests, refactor

#432 Method run debugging
  coreblocks/transactions/core.py
  test/common.py
Labels: transactions, tests

#449 Synthesis benchmark for FUs
  constants/ecp5_pinout.py
  constants/ecp5_platforms.py
  coreblocks/fu/div_unit.py
  coreblocks/params/configurations.py
  scripts/synthesize.py
  stubs/amaranth/build/__init__.pyi
  stubs/amaranth/build/dsl.pyi
  stubs/amaranth/build/plat.pyi
  stubs/amaranth/build/res.pyi
Labels: tests, optimization
