Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-04, with the labels that each got.

#273 DependencyManager: ListKey, key locking
  coreblocks/params/fu_params.py
Labels: enhancement

#265 Make 'enable' parameter in the method mock a lambda
  coreblocks/stages/retirement.py
  test/common.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/stages/test_retirement.py
  test/transactions/test_transaction_lib.py
Labels: tests, refactor

#275 Core generation configurations
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  scripts/core_graph.py
  scripts/gen_verilog.py
  scripts/synthesize.py
  test/common.py
  test/frontend/test_decode.py
  test/frontend/test_decoder.py
  test/frontend/test_fetch.py
  test/fu/functional_common.py
  test/fu/test_alu.py
  test/fu/test_jb_unit.py
  test/fu/test_mul_unit.py
  test/fu/test_unsigned_mul_unit.py
  test/fu/test_zbs.py
  test/lsu/test_dummylsu.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/stages/test_retirement.py
  test/structs_common/test_csr.py
  test/structs_common/test_reorder_buffer.py
  test/structs_common/test_rs.py
  test/test_core.py
Labels: enhancement

#274 Bump linter versions
  coreblocks/fu/mul_unit.py
  coreblocks/stages/func_blocks_unifier.py
  coreblocks/transactions/lib.py
  requirements-dev.txt
  test/frontend/test_decode.py
  test/frontend/test_fetch.py
  test/fu/test_alu.py
  test/scheduler/test_wakeup_select.py
  test/structs_common/test_csr.py
  test/transactions/test_adapter.py
  test/transactions/test_assign.py
  test/transactions/test_transactions.py
Labels: refactor

#278 Add a function aligning numbers and a function for yielding for many cycles
  coreblocks/utils/utils.py
  test/common.py
  test/frontend/test_fetch.py
  test/test_core.py
  test/transactions/test_transaction_lib.py
  test/utils/test_utils.py
Labels: enhancement, tests

#279 Fix FreeRF FIFO initialization
  coreblocks/core.py
  coreblocks/utils/fifo.py
  test/test_core.py
  test/utils/test_fifo.py
Labels: bug

#258 Instruction Cache 🚀
  coreblocks/frontend/icache.py
  coreblocks/params/__init__.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/params/icache_params.py
  coreblocks/params/layouts.py
  docs/components/icache.md
  docs/index.md
  test/frontend/test_icache.py
Labels: enhancement

#284 Decoder fix for shift immediate handling
  coreblocks/frontend/decoder.py
  test/frontend/test_decoder.py
Labels: bug

#283 LSU addressing fix
  coreblocks/lsu/dummyLsu.py
  test/lsu/test_dummylsu.py
Labels: bug

#282 Decoder: set invalid registers to 0 and fix CSR decoding
  coreblocks/frontend/decode.py
  coreblocks/frontend/decoder.py
  coreblocks/params/layouts.py
  coreblocks/params/optypes.py
  coreblocks/structs_common/csr.py
  test/frontend/test_decode.py
  test/frontend/test_decoder.py
  test/scheduler/test_scheduler.py
  test/structs_common/test_csr.py
Labels: bug

#267 CSR integration and improvements
  coreblocks/core.py
  coreblocks/frontend/fetch.py
  coreblocks/params/configurations.py
  coreblocks/params/dependencies.py
  coreblocks/params/keys.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/csr_generic.py
  coreblocks/structs_common/rob.py
  coreblocks/utils/utils.py
  scripts/gen_verilog.py
  test/asm/csr.asm
  test/stages/test_retirement.py
  test/structs_common/test_csr.py
  test/structs_common/test_reorder_buffer.py
  test/test_core.py
Labels: enhancement, microarch

#292 Proxy fix
  coreblocks/transactions/core.py
Labels: bug

#291 Add multiplication tests (cocotb)
  .github/workflows/cocotb.yml
  test/cocotb/test.py
  test/external/riscv-tests/Makefile
Labels: tests

#257 Proof of concept instruction decoding
  coreblocks/fu/alu.py
  coreblocks/fu/fu_decoder.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/mul_unit.py
  coreblocks/fu/zbs.py
  test/fu/test_fu_decoder.py
  test/fu/test_zbs.py
Labels: refactor

#302 Added timeouts for workflows.
  .github/workflows/benchmark.yml
  .github/workflows/cocotb.yml
  .github/workflows/deploy_gh_pages.yml
  .github/workflows/deploy_wiki.yml
  .github/workflows/main.yml
Labels: infrastructure

#308 Transaction core refactor
  coreblocks/transactions/core.py
Labels: transactions, refactor

#307 Add instruction cache bypass
  coreblocks/frontend/icache.py
  test/frontend/test_icache.py
Labels: enhancement

#271 Make the fetch unit use instruction cache
  coreblocks/core.py
  coreblocks/frontend/fetch.py
  coreblocks/frontend/icache.py
  coreblocks/params/configurations.py
  coreblocks/params/icache_params.py
  test/cocotb/test.py
  test/frontend/test_fetch.py
  test/test_core.py
Labels: enhancement, refactor
