Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-11, with the labels that each got.

#466 Script to generate signature from test ELFs
  coreblocks/utils/utils.py
  scripts/run_signature.py
  test/external/riscof/coreblocks/env/link.ld
  test/external/riscof/coreblocks/env/model_test.h
  test/regression/cocotb/signature.Makefile
  test/regression/cocotb/signature_entrypoint.py
  test/regression/memory.py
  test/regression/signature.py
  test/utils/test_utils.py
Labels: tests

#500 Fix build after #466
  test/regression/memory.py
Labels: bug

#470 Fix zbs and DecoderManager docstrings
  coreblocks/fu/fu_decoder.py
  coreblocks/fu/zbs.py
Labels: documentation

#502 Fix build, for real this time
  test/regression/memory.py
Labels: bug

#503 Autumn cleaning - move coreblocks utils to transactron
  coreblocks/core.py
  coreblocks/frontend/fetch.py
  coreblocks/frontend/icache.py
  coreblocks/frontend/rvc.py
  coreblocks/fu/alu.py
  coreblocks/fu/div_unit.py
  coreblocks/fu/exception.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/mul_unit.py
  coreblocks/fu/shift_unit.py
  coreblocks/fu/zbc.py
  coreblocks/fu/zbs.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/instr.py
  coreblocks/params/layouts.py
  coreblocks/peripherals/wishbone.py
  coreblocks/scheduler/scheduler.py
  coreblocks/scheduler/wakeup_select.py
  coreblocks/structs_common/csr.py
  coreblocks/utils/__init__.py
  coreblocks/utils/protocols.py
  scripts/gen_verilog.py
  scripts/synthesize.py
  test/common/functions.py
  test/common/infrastructure.py
  test/common/sugar.py
  test/common/testbenchio.py
  test/frontend/test_fetch.py
  test/frontend/test_rvc.py
  test/gtkw_extension.py
  test/regression/memory.py
  test/structs_common/test_exception.py
  test/test_core.py
  test/transactions/test_assign.py
  test/transactions/test_simultaneous.py
  test/transactions/test_transaction_lib.py
  test/utils/test_fifo.py
  test/utils/test_onehotswitch.py
  test/utils/test_utils.py
  transactron/_utils.py
  transactron/core.py
  transactron/lib/reqres.py
  transactron/lib/simultaneous.py
  transactron/lib/storage.py
  transactron/lib/transformers.py
  transactron/tracing.py
  transactron/utils/__init__.py
  transactron/utils/_typing.py
  transactron/utils/debug_signals.py
  transactron/utils/fifo.py
  transactron/utils/utils.py
Labels: refactor

#505 Faster Wishbone
  coreblocks/frontend/icache.py
  coreblocks/peripherals/wishbone.py
  test/frontend/test_icache.py
  test/peripherals/test_wishbone.py
  transactron/core.py
Labels: optimization

#501 Autumn cleaning: layouts
  coreblocks/core.py
  coreblocks/frontend/decode.py
  coreblocks/frontend/fetch.py
  coreblocks/fu/fu_decoder.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/genparams.py
  coreblocks/params/layouts.py
  coreblocks/stages/backend.py
  coreblocks/stages/rs_func_block.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/rs.py
  test/frontend/test_decode.py
  test/frontend/test_fetch.py
  test/lsu/test_dummylsu.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/stages/test_backend.py
  test/structs_common/test_csr.py
  test/structs_common/test_rs.py
  test/test_core.py
  transactron/utils/_typing.py
  transactron/utils/utils.py
Labels: refactor

#495 Cache regression tests in workflow
  .github/workflows/main.yml
Labels: infrastructure

#511 DummyLSU refactored again
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/layouts.py
Labels: refactor, optimization

#520 RAT tests
  test/structs_common/test_rat.py
Labels: tests

#521 Transaction graph and docs cleanup
  docs/Current_graph.md
  docs/assumptions.md
  docs/current-graph.md
  docs/development-environment.md
  docs/home.md
  docs/index.md
  docs/miscellany/exceptions-summary.md
  docs/problem-checklist.md
  docs/scheduler/overview.md
  docs/shared-structs/implementation/rs-impl.md
  docs/shared-structs/rs.md
  docs/synthesis/synthesis.md
  docs/transactions.md
Labels: documentation

#525 Simpler way of using method transformations
  test/transactions/test_transaction_lib.py
  transactron/lib/transformers.py
Labels: transactions
