Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-05, with the labels that each got.

#317 Module connector
  coreblocks/utils/utils.py
Labels: enhancement

#318 Refactor of ROB test
  test/structs_common/test_reorder_buffer.py
Labels: tests, refactor

#324 Fix `schedule_before`
  coreblocks/transactions/core.py
  test/transactions/test_transactions.py
Labels: bug

#276 Nestable transactions
  coreblocks/transactions/core.py
  docs/Transactions.md
  test/transactions/test_transactions.py
Labels: transactions

#314 Remove anonymous submodules
  coreblocks/transactions/core.py
  test/common.py
Labels: refactor

#319 Refactor tests with TransactionModule
  coreblocks/transactions/core.py
  coreblocks/utils/utils.py
  scripts/core_graph.py
  test/common.py
  test/frontend/test_decode.py
  test/frontend/test_fetch.py
  test/frontend/test_icache.py
  test/fu/functional_common.py
  test/fu/test_alu.py
  test/fu/test_unsigned_mul_unit.py
  test/lsu/test_dummylsu.py
  test/peripherals/test_wishbone.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/stages/test_retirement.py
  test/structs_common/test_csr.py
  test/structs_common/test_reorder_buffer.py
  test/structs_common/test_rs.py
  test/test_core.py
  test/transactions/test_adapter.py
  test/transactions/test_methods.py
  test/transactions/test_transaction_lib.py
  test/transactions/test_transactions.py
  test/utils/test_fifo.py
Labels: refactor

#321 Refactor method filter test
  test/transactions/test_transaction_lib.py
Labels: refactor

#330 Fix pushing CI docs
  ci/build_docs.sh
  ci/push_docs.sh
  ci/push_gh_pages.sh
  docs/Home.md
  docs/wiki_exclude
Labels: bug, documentation

#334 Optype refactor
  coreblocks/fu/alu.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/mul_unit.py
  coreblocks/fu/zbs.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/fu_params.py
  coreblocks/scheduler/scheduler.py
  coreblocks/stages/func_blocks_unifier.py
  coreblocks/stages/rs_func_block.py
  coreblocks/structs_common/csr.py
  coreblocks/utils/protocols.py
  test/fu/test_jb_unit.py
  test/scheduler/test_scheduler.py
Labels: refactor

#333 ZBA enable flag
  coreblocks/fu/alu.py
  coreblocks/fu/fu_decoder.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/mul_unit.py
  coreblocks/fu/zbs.py
  test/fu/test_alu.py
  test/fu/test_fu_decoder.py
  test/fu/test_jb_unit.py
Labels: refactor

#339 Fix debug_signals method bug introduced in #334
  coreblocks/stages/func_blocks_unifier.py
Labels: bug

#336 Fix method_uses in the transaction manager
  coreblocks/transactions/core.py
Labels: bug, transactions

#345 One-hot implementation change
  coreblocks/utils/utils.py
Labels: optimization

#346 Method argument passing optimization
  coreblocks/transactions/core.py
Labels: optimization

#349 Add Dockerfile for RISCV toolchain
  docker/riscv-toolchain.Dockerfile
Labels: infrastructure

#340 Shift Alu
  coreblocks/fu/alu.py
  coreblocks/fu/shift_unit.py
  coreblocks/params/configurations.py
  test/fu/test_alu.py
  test/fu/test_shift_unit.py
Labels: refactor

#335 Refactor cocotb tests
  .github/workflows/cocotb.yml
  .github/workflows/main.yml
  .gitignore
  scripts/run_tests.py
  test/cocotb/test.py
  test/common.py
  test/external/riscv-tests/Makefile
  test/external/riscv-tests/environment/custom/link.ld
  test/external/riscv-tests/environment/custom/riscv_test.h
  test/regression/__init__.py
  test/regression/benchmark.py
  test/regression/cocotb.py
  test/regression/cocotb/test.Makefile
  test/regression/cocotb/test_entrypoint.py
  test/regression/common.py
  test/regression/memory.py
  test/regression/pysim.py
  test/regression/test.py
  test/utils/test_onehotswitch.py
Labels: tests, refactor

#353 Yet another debug log fix.
  coreblocks/transactions/core.py
Labels: enhancement

#354 Popcount
  coreblocks/utils/utils.py
  test/utils/test_utils.py
Labels: enhancement

#361 Fix a bug in JumpBranch Unit
  coreblocks/fu/jumpbranch.py
  test/fu/test_jb_unit.py
Labels: bug

#364 Add support for zmmul extension in the toolchain
  docker/riscv-toolchain.Dockerfile
Labels: infrastructure

#368 Better names for transaction signals
  coreblocks/transactions/core.py
Labels: enhancement

#371 Nicer UnifierKey
  coreblocks/params/dependencies.py
  coreblocks/params/keys.py
Labels: enhancement

#370 Precommit
  coreblocks/core.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/keys.py
  coreblocks/params/layouts.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/rob.py
  test/lsu/test_dummylsu.py
  test/stages/test_retirement.py
  test/structs_common/test_csr.py
  test/structs_common/test_reorder_buffer.py
Labels: enhancement, microarch
