Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-10, with the labels that each got.

#461 Fix pipeline
  coreblocks/params/instr.py
  coreblocks/structs_common/exception.py
  coreblocks/utils/utils.py
  requirements.txt
  stubs/amaranth/hdl/ast.pyi
  stubs/amaranth/hdl/ir.pyi
  stubs/amaranth/lib/data.pyi
  test/transactions/test_transaction_lib.py
Labels: bug, priority

#464 Autumn cleaning part 2 - split transactron/lib.py
  coreblocks/params/keys.py
  transactron/lib.py
  transactron/lib/__init__.py
  transactron/lib/adapters.py
  transactron/lib/buttons.py
  transactron/lib/connectors.py
  transactron/lib/reqres.py
  transactron/lib/simultaneous.py
  transactron/lib/storage.py
  transactron/lib/transformers.py
Labels: refactor

#479 Autumn cleaning: types
  coreblocks/fu/div_unit.py
  coreblocks/fu/mul_unit.py
  coreblocks/scheduler/scheduler.py
  coreblocks/stages/func_blocks_unifier.py
  coreblocks/structs_common/rs.py
  coreblocks/utils/_typing.py
  coreblocks/utils/utils.py
  transactron/_utils.py
  transactron/lib/transformers.py
Labels: refactor

#490 Fix tests with binutils 2.41
  test/test_core.py
Labels: bug, tests

#491 Extend Transactron introduction
  docs/Transactions.md
Labels: documentation

#477 Autumn cleaning part 4 - split test/common.py
  coreblocks/utils/_typing.py
  test/common.py
  test/common/__init__.py
  test/common/functions.py
  test/common/infrastructure.py
  test/common/sugar.py
  test/common/testbenchio.py
  test/fu/test_alu.py
  test/fu/test_div_unit.py
  test/fu/test_jb_unit.py
  test/fu/test_mul_unit.py
  test/lsu/test_dummylsu.py
  transactron/_utils.py
Labels: tests, refactor
