Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-06, with the labels that each got.

#379 Instruction decoder refactor
  coreblocks/frontend/decode.py
  coreblocks/frontend/decoder.py
  test/frontend/test_decode.py
  test/frontend/test_decoder.py
Labels: refactor

#372 Parametrize rs_entries in RSLayouts
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/configurations.py
  coreblocks/params/fu_params.py
  coreblocks/params/genparams.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/stages/rs_func_block.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/rs.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/structs_common/test_rs.py
Labels: bug, enhancement

#369 ZBB extension
  coreblocks/frontend/decoder.py
  coreblocks/fu/alu.py
  coreblocks/fu/shift_unit.py
  coreblocks/params/configurations.py
  coreblocks/params/isa.py
  coreblocks/params/optypes.py
  coreblocks/utils/utils.py
  test/frontend/test_decoder.py
  test/fu/test_alu.py
  test/fu/test_shift_unit.py
  test/params/test_configurations.py
  test/utils/test_utils.py
Labels: enhancement

#387 Remove dummy sync signal
  coreblocks/frontend/decoder.py
  coreblocks/fu/jumpbranch.py
  test/common.py
  test/fu/test_fu_decoder.py
  test/scheduler/test_wakeup_select.py
  test/transactions/test_adapter.py
  test/transactions/test_methods.py
  test/transactions/test_transaction_lib.py
  test/transactions/test_transactions.py
  test/utils/test_onehotswitch.py
  test/utils/test_utils.py
Labels: refactor

#347 Simultaneous transactions
  coreblocks/transactions/core.py
  coreblocks/transactions/lib.py
  test/transactions/test_simultaneous.py
  test/transactions/test_transaction_lib.py
Labels: enhancement, transactions, review needed

#391 Try-product combiner
  coreblocks/params/keys.py
  coreblocks/transactions/lib.py
  test/transactions/test_transaction_lib.py
Labels: transactions

#260 Multiport fifo
  coreblocks/utils/fifo.py
  test/utils/test_fifo.py
Labels: enhancement

#388 Encoding uniqueness
  coreblocks/frontend/decoder.py
  test/frontend/test_decoder.py
Labels: tests

#304 MemoryBank and Serializer
  coreblocks/transactions/lib.py
  coreblocks/utils/fifo.py
  stubs/amaranth/utils.pyi
  test/common.py
  test/test_core.py
  test/transactions/test_transaction_lib.py
Labels: enhancement, review needed

#407 Synthesize different core versions
  .github/workflows/benchmark.yml
  scripts/synthesize.py
Labels: infrastructure
