Repository kuznia-rdzeni/coreblocks, pull requests merged in 2023-12, with the labels that each got.

#513 Run riscv-arch-test suite in CI
  .github/workflows/main.yml
  ci/riscof_compare.sh
  ci/riscof_run_makefile.sh
  scripts/run_signature.py
  test/external/riscof/config.ini
  test/external/riscof/coreblocks/coreblocks_isa.yaml
  test/external/riscof/coreblocks/coreblocks_platform.yaml
  test/external/riscof/coreblocks/riscof_coreblocks.py
  test/external/riscof/spike_simple/__init__.py
  test/external/riscof/spike_simple/env/link.ld
  test/external/riscof/spike_simple/env/model_test.h
  test/external/riscof/spike_simple/riscof_spike_simple.py
  test/external/riscof/spike_simple/spike_simple_isa.yaml
  test/external/riscof/spike_simple/spike_simple_platform.yaml
  test/regression/signature.py
Labels: infrastructure

#533 Fix riscv-test job dependencies
  .github/workflows/main.yml
Labels: bug, infrastructure

#510 Implement physical memory attributes (PMA) for memory-mapped IO (MMIO)
  coreblocks/lsu/dummyLsu.py
  coreblocks/lsu/pma.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/params/layouts.py
  test/lsu/test_pma.py
Labels: enhancement

#534 Clear ExcepionCauseRegister after flushing core
  coreblocks/core.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/exception.py
  test/asm/exception_handler.asm
  test/stages/test_retirement.py
  test/test_core.py
Labels: bug

#535 Transactron statistics and info
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  transactron/core.py
  transactron/utils/utils.py
Labels: transactions

#519 Autumn cleaning - remove _utils.py and utils.py in transactron
  coreblocks/core.py
  coreblocks/frontend/fetch.py
  coreblocks/fu/alu.py
  coreblocks/fu/div_unit.py
  coreblocks/params/layouts.py
  coreblocks/peripherals/wishbone.py
  scripts/gen_verilog.py
  scripts/synthesize.py
  test/common/__init__.py
  test/common/testbenchio.py
  test/fu/test_alu.py
  test/fu/test_div_unit.py
  test/fu/test_jb_unit.py
  test/fu/test_mul_unit.py
  test/gtkw_extension.py
  test/lsu/test_dummylsu.py
  test/regression/memory.py
  test/structs_common/test_exception.py
  test/transactions/test_assign.py
  test/transactions/test_simultaneous.py
  test/transactions/test_transactions.py
  test/utils/test_fifo.py
  transactron/_utils.py
  transactron/core.py
  transactron/lib/__init__.py
  transactron/lib/fifo.py
  transactron/lib/reqres.py
  transactron/utils/__init__.py
  transactron/utils/_typing.py
  transactron/utils/amaranth_ext/__init__.py
  transactron/utils/amaranth_ext/elaboratables.py
  transactron/utils/amaranth_ext/functions.py
  transactron/utils/assign.py
  transactron/utils/data_repr.py
  transactron/utils/transactron_helpers.py
  transactron/utils/utils.py
Labels: refactor

#532 Asynchronous interrupts
  coreblocks/core.py
  coreblocks/frontend/fetch.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/priv.py
  coreblocks/params/configurations.py
  coreblocks/params/isa.py
  coreblocks/params/keys.py
  coreblocks/params/layouts.py
  coreblocks/params/optypes.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/interrupt_controller.py
  test/asm/interrupt.asm
  test/frontend/test_decoder.py
  test/fu/functional_common.py
  test/params/test_configurations.py
  test/stages/test_retirement.py
  test/structs_common/test_csr.py
  test/test_core.py
Labels: enhancement, microarch

#454 Update synthesis docs
  docs/synthesis/synthesis.md
Labels: documentation

#524 AMBA AXI4-Lite master
  coreblocks/peripherals/axi_lite.py
  test/peripherals/test_axi_lite.py
Labels: enhancement

#537 Refactor runnable signal of transactions
  transactron/core.py
Labels: transactions, refactor

#541 GenParams renaming
  coreblocks/core.py
  coreblocks/frontend/decode.py
  coreblocks/frontend/decoder.py
  coreblocks/frontend/fetch.py
  coreblocks/frontend/rvc.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/mul_unit.py
  coreblocks/fu/unsigned_multiplication/common.py
  coreblocks/fu/unsigned_multiplication/fast_recursive.py
  coreblocks/fu/unsigned_multiplication/sequence.py
  coreblocks/fu/unsigned_multiplication/shift.py
  coreblocks/params/layouts.py
  coreblocks/stages/backend.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/csr_generic.py
  coreblocks/structs_common/exception.py
  coreblocks/structs_common/instr_counter.py
  test/frontend/test_decode.py
  test/frontend/test_decoder.py
  test/frontend/test_fetch.py
  test/frontend/test_icache.py
  test/frontend/test_rvc.py
  test/fu/functional_common.py
  test/fu/test_unsigned_mul_unit.py
  test/lsu/test_dummylsu.py
  test/lsu/test_pma.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/structs_common/test_csr.py
  test/structs_common/test_exception.py
  test/structs_common/test_reorder_buffer.py
  test/structs_common/test_rs.py
  test/test_core.py
Labels: refactor

#550 Fix get_caller_class_name to handle calls in elaborate
  test/transactions/test_transactions.py
  transactron/utils/transactron_helpers.py
Labels: bug

#542 Source locations for transactions and methods
  transactron/core.py
  transactron/lib/adapters.py
  transactron/lib/buttons.py
  transactron/lib/connectors.py
  transactron/lib/fifo.py
  transactron/lib/reqres.py
  transactron/lib/simultaneous.py
  transactron/lib/storage.py
  transactron/lib/transformers.py
  transactron/utils/_typing.py
  transactron/utils/transactron_helpers.py
Labels: enhancement

#548 Retirement refactor
  coreblocks/core.py
  coreblocks/params/layouts.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/rat.py
  test/stages/test_retirement.py
  test/structs_common/test_rat.py
Labels: refactor
