Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-01, with the labels that each got.

#551 Exclusive branches
  coreblocks/fu/jumpbranch.py
  coreblocks/structs_common/csr.py
  test/transactions/test_branches.py
  test/transactions/test_methods.py
  transactron/core.py
Labels: enhancement, transactions

#545 Fix performance problems after #532
  coreblocks/frontend/fetch.py
  coreblocks/params/layouts.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/exception.py
  test/structs_common/test_exception.py
Labels: optimization

#544 Move dependency related classes to Transactron
  coreblocks/core.py
  coreblocks/fu/exception.py
  coreblocks/fu/jumpbranch.py
  coreblocks/fu/priv.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/__init__.py
  coreblocks/params/genparams.py
  coreblocks/params/keys.py
  coreblocks/stages/func_blocks_unifier.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/exception.py
  coreblocks/structs_common/interrupt_controller.py
  coreblocks/utils/protocols.py
  test/fu/functional_common.py
  test/lsu/test_dummylsu.py
  test/lsu/test_pma.py
  test/structs_common/test_csr.py
  transactron/lib/dependencies.py
  transactron/lib/transformers.py
  transactron/utils/__init__.py
  transactron/utils/depcache.py
  transactron/utils/dependencies.py
Labels: refactor

#553 Add pytest - step 1
  coreblocks/frontend/fetch.py
  coreblocks/frontend/icache.py
  coreblocks/frontend/rvc.py
  coreblocks/fu/alu.py
  coreblocks/fu/shift_unit.py
  coreblocks/params/instr.py
  coreblocks/peripherals/wishbone.py
  scripts/core_graph.py
  stubs/amaranth/hdl/ast.pyi
  test/common/infrastructure.py
  test/frontend/test_decode.py
  test/frontend/test_fetch.py
  test/frontend/test_rvc.py
  test/stages/test_retirement.py
  test/structs_common/test_rs.py
  test/test_core.py
  test/transactions/test_adapter.py
  transactron/utils/amaranth_ext/elaboratables.py
Labels: refactor

#558 Allow additional method arguments in Adapter
  test/stages/test_retirement.py
  transactron/lib/adapters.py
  transactron/utils/_typing.py
Labels: bug

#540 Simplify adding mock processes
  test/common/infrastructure.py
  test/common/sugar.py
  test/frontend/test_fetch.py
  test/frontend/test_icache.py
  test/lsu/test_dummylsu.py
  test/lsu/test_pma.py
  test/stages/test_retirement.py
  test/structs_common/test_exception.py
  test/transactions/test_simultaneous.py
  test/transactions/test_transaction_lib.py
Labels: enhancement, question, infrastructure

#562 Retirement test fix
  coreblocks/params/layouts.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/rob.py
  test/stages/test_retirement.py
Labels: bug, tests

#563 More readable exception on invalid def_method_mock function
  transactron/utils/transactron_helpers.py
Labels: tests

#565 Remove unneeded random_wait
  test/common/infrastructure.py
  test/fu/functional_common.py
  test/fu/test_unsigned_mul_unit.py
  test/lsu/test_dummylsu.py
  test/scheduler/test_rs_selection.py
  test/stages/test_backend.py
  test/structs_common/test_csr.py
  test/transactions/test_transaction_lib.py
Labels: tests, refactor

#568 Fix core freezing during flushing
  coreblocks/params/keys.py
  coreblocks/params/layouts.py
  coreblocks/scheduler/scheduler.py
  coreblocks/stages/backend.py
  coreblocks/stages/retirement.py
  test/scheduler/test_scheduler.py
Labels: bug, microarch

#547 Transaction profiles
  .github/workflows/main.yml
  .gitignore
  docs/development-environment.md
  requirements-dev.txt
  scripts/run_tests.py
  scripts/tprof.py
  test/common/__init__.py
  test/common/infrastructure.py
  test/common/profiler.py
  test/transactions/test_methods.py
  transactron/core.py
  transactron/profiler.py
Labels: transactions, tests

#570 Refactor naming in coreblocks frontend
  coreblocks/core.py
  coreblocks/frontend/decode_stage.py
  coreblocks/frontend/instr_decoder.py
  coreblocks/frontend/instr_description.py
  test/frontend/test_decode_stage.py
  test/frontend/test_instr_decoder.py
  test/structs_common/test_csr.py
Labels: refactor
