Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-10, with the labels that each got.

#722 More uses of av_comb, slight refactor of RF
  coreblocks/core_structs/rf.py
  coreblocks/func_blocks/fu/alu.py
  coreblocks/func_blocks/fu/div_unit.py
  coreblocks/func_blocks/fu/mul_unit.py
  coreblocks/func_blocks/fu/shift_unit.py
  coreblocks/func_blocks/fu/zbc.py
  coreblocks/func_blocks/fu/zbs.py
Labels: refactor, benchmark

#729 User Mode and remaining mstatus fields
  coreblocks/arch/csr_address.py
  coreblocks/arch/isa_consts.py
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/keys.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/priv/csr/aliased.py
  coreblocks/priv/csr/csr_instances.py
  coreblocks/priv/traps/interrupt_controller.py
  test/asm/user_mode.asm
  test/backend/test_retirement.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/functional_common.py
  test/test_core.py
Labels: enhancement

#712 Implement full `mtval`
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/frontend/decoder/decode_stage.py
  coreblocks/frontend/decoder/instr_decoder.py
  coreblocks/frontend/decoder/rvc.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/lsu_requester.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/layouts.py
  coreblocks/priv/csr/csr_instances.py
  coreblocks/priv/traps/exception.py
  test/asm/mtval.asm
  test/frontend/test_instr_decoder.py
  test/frontend/test_rvc.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/fu/test_exception_unit.py
  test/func_blocks/fu/test_jb_unit.py
  test/func_blocks/lsu/test_dummylsu.py
  test/priv/traps/test_exception.py
  test/test_core.py
  transactron/utils/transactron_helpers.py
Labels: enhancement

#735 Fix WFI resume on mstatus.MIE disabled
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/keys.py
  coreblocks/priv/traps/interrupt_controller.py
  test/asm/user_mode.asm
  test/asm/wfi_no_mie.asm
  test/test_core.py
Labels: bug
