Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-06, with the labels that each got.

#711 Add support for target prediction in JumpBranch unit
  coreblocks/frontend/frontend.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/interface/keys.py
  coreblocks/interface/layouts.py
  test/func_blocks/fu/test_jb_unit.py
Labels: enhancement, microarch

#713 Fix build after #705
  .github/workflows/benchmark.yml
Labels: bug, infrastructure, benchmark

#716 Restore logging handler
  test/transactron/testing/test_log.py
  transactron/testing/infrastructure.py
Labels: bug
