Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-11, with the labels that each got.

#736 Multiport `MemoryBank`
  test/transactron/lib/test_transaction_lib.py
  transactron/lib/storage.py
Labels: enhancement

#739 Changeable underlying memory in MemoryBank
  transactron/lib/storage.py
Labels: enhancement

#677 Precommit using validate_arguments
  coreblocks/backend/retirement.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/layouts.py
  test/backend/test_retirement.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  transactron/testing/testbenchio.py
Labels: refactor

#743 Implement `misa` CSR
  coreblocks/priv/csr/csr_instances.py
Labels: enhancement

#728 FPU rounding module
  coreblocks/func_blocks/fu/fpu/__init__.py
  coreblocks/func_blocks/fu/fpu/fpu_common.py
  coreblocks/func_blocks/fu/fpu/fpu_error_module.py
  coreblocks/func_blocks/fu/fpu/fpu_rounding_module.py
  test/func_blocks/fu/fpu/test_fpu_error.py
  test/func_blocks/fu/fpu/test_fpu_rounding.py
Labels: enhancement

#750 Fix synthesis of some configurations
  coreblocks/core.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/frontend/frontend.py
  coreblocks/params/configurations.py
  test/params/test_configurations.py
  test/test_core.py
  transactron/utils/dependencies.py
Labels: bug

#756 LiteX support changes
  coreblocks/core.py
  coreblocks/params/configurations.py
  test/params/test_configurations.py
  test/test_core.py
Labels: enhancement

#759 RF using async memory
  coreblocks/core_structs/rf.py
  test/test_core.py
Labels: refactor, benchmark

#747 Implement zicond
  coreblocks/arch/isa.py
  coreblocks/arch/isa_consts.py
  coreblocks/arch/optypes.py
  coreblocks/frontend/decoder/instr_description.py
  coreblocks/func_blocks/fu/alu.py
  coreblocks/params/configurations.py
  test/frontend/test_instr_decoder.py
  test/func_blocks/fu/test_alu.py
  test/params/test_configurations.py
Labels: enhancement
