Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-04, with the labels that each got.

#631 Refactor RISC-V instruction models
  coreblocks/frontend/decoder/isa.py
  coreblocks/frontend/decoder/rvc.py
  coreblocks/params/instr.py
  test/frontend/test_rvc.py
  test/params/test_instr.py
  test/test_core.py
Labels: refactor

#636 Fix instruction cache refilling bug
  coreblocks/cache/icache.py
  test/cache/test_icache.py
  transactron/lib/fifo.py
  transactron/lib/reqres.py
Labels: bug

#637 Add TaggedCounter
  coreblocks/func_blocks/fu/alu.py
  coreblocks/func_blocks/fu/jumpbranch.py
  test/transactron/test_metrics.py
  transactron/lib/metrics.py
Labels: enhancement

#632 More metrics for RF, RS and ROB
  coreblocks/cache/icache.py
  coreblocks/core_structs/rf.py
  coreblocks/core_structs/rob.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/common/rs.py
  coreblocks/func_blocks/fu/common/rs_func_block.py
  coreblocks/func_blocks/lsu/dummyLsu.py
  coreblocks/params/configurations.py
  coreblocks/params/fu_params.py
  test/regression/cocotb/benchmark.Makefile
  test/regression/cocotb/signature.Makefile
  test/regression/cocotb/test.Makefile
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/structs_common/test_rs.py
  test/transactions/test_transaction_lib.py
  test/transactron/test_metrics.py
  transactron/lib/metrics.py
  transactron/lib/storage.py
Labels: enhancement

#639 Add Pipe module
  test/transactions/test_transaction_lib.py
  transactron/lib/connectors.py
Labels: enhancement

#638 Fix yet another bug in the instruction cache
  coreblocks/cache/icache.py
  test/cache/test_icache.py
Labels: bug

#634 FIFO reservation station
  coreblocks/func_blocks/fu/common/fifo_rs.py
  coreblocks/func_blocks/fu/common/rs.py
  coreblocks/scheduler/wakeup_select.py
  test/structs_common/test_rs.py
Labels: enhancement

#641 Cache cocotb-config
  test/regression/cocotb/cocotb-config
  test/regression/test_regression.py
Labels: infrastructure, optimization

#640 Support ArrayLayouts in assign
  test/transactions/test_assign.py
  transactron/utils/assign.py
Labels: enhancement

#643 Fix typo in assign.py
  transactron/utils/assign.py
Labels: bug

#635 DummyLSU as a FU
  coreblocks/func_blocks/fu/common/rs_func_block.py
  coreblocks/func_blocks/fu/lsu/__init__.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/pma.py
  coreblocks/interface/layouts.py
  coreblocks/params/configurations.py
  test/lsu/test_dummylsu.py
  test/lsu/test_pma.py
Labels: enhancement, optimization

#645 Fix logging handler connection
  transactron/testing/logging.py
Labels: bug, infrastructure

#647 Fix LSU FENCE issue
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
Labels: bug

#649 Add support for 'fence.i' instruction
  .gitignore
  coreblocks/core.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/keys.py
  test/params/test_configurations.py
  test/regression/conftest.py
  test/regression/memory.py
  test/regression/test_regression.py
Labels: enhancement

#655 ROB refactor
  coreblocks/core_structs/rob.py
  coreblocks/interface/layouts.py
  test/scheduler/test_scheduler.py
Labels: refactor

#656 Remove assertNotNone typechecker workarounds
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/structs_common/test_csr.py
  test/transactions/test_transaction_lib.py
Labels: refactor

#652 Flexible CSRs
  coreblocks/func_blocks/csr/csr.py
  coreblocks/interface/keys.py
  coreblocks/interface/layouts.py
  coreblocks/priv/csr/csr_register.py
  test/structs_common/test_csr.py
Labels: enhancement

#630 Superscalar frontend
  coreblocks/core.py
  coreblocks/frontend/decoder/decode_stage.py
  coreblocks/frontend/decoder/optypes.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/interface/layouts.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  test/frontend/test_fetch.py
  test/regression/cocotb/benchmark.Makefile
  test/regression/cocotb/signature.Makefile
  test/regression/cocotb/test.Makefile
  test/test_core.py
  transactron/lib/fifo.py
  transactron/testing/logging.py
Labels: enhancement

#653 Scheduler refactor
  coreblocks/scheduler/scheduler.py
Labels: refactor

#659 Reduce number of cycles in core tests
  test/test_core.py
Labels: tests

#644 Move tests after #620
  test/backend/__init__.py
  test/backend/test_annoucement.py
  test/backend/test_retirement.py
  test/core_structs/__init__.py
  test/core_structs/test_rat.py
  test/core_structs/test_reorder_buffer.py
  test/func_blocks/__init__.py
  test/func_blocks/csr/__init__.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/__init__.py
  test/func_blocks/fu/common/__init__.py
  test/func_blocks/fu/common/test_rs.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/fu/test_alu.py
  test/func_blocks/fu/test_div_unit.py
  test/func_blocks/fu/test_exception_unit.py
  test/func_blocks/fu/test_fu_decoder.py
  test/func_blocks/fu/test_jb_unit.py
  test/func_blocks/fu/test_mul_unit.py
  test/func_blocks/fu/test_shift_unit.py
  test/func_blocks/fu/test_unsigned_mul_unit.py
  test/func_blocks/fu/test_zbc.py
  test/func_blocks/fu/test_zbs.py
  test/func_blocks/lsu/__init__.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  test/priv/__init__.py
  test/priv/traps/__init__.py
  test/priv/traps/test_exception.py
  test/transactron/core/__init__.py
  test/transactron/core/test_transactions.py
  test/transactron/lib/__init__.py
  test/transactron/lib/test_fifo.py
  test/transactron/lib/test_transaction_lib.py
  test/transactron/test_adapter.py
  test/transactron/test_assign.py
  test/transactron/test_branches.py
  test/transactron/test_methods.py
  test/transactron/test_simultaneous.py
  test/transactron/utils/__init__.py
  test/transactron/utils/test_onehotswitch.py
  test/transactron/utils/test_utils.py
Labels: refactor

#648 Turn off printing pytest logs
  pytest.ini
Labels: bug

#651 Type CoreConfiguration.replace
  coreblocks/params/configurations.py
  test/cache/test_icache.py
Labels: nice to have

#662 Reverse precommit
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/keys.py
  test/backend/test_retirement.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
Labels: refactor

#660 Run benchmarks on every PR
  .github/workflows/benchmark.yml
  ci/print_benchmark_summary.py
  scripts/lint.sh
  scripts/run_benchmarks.py
  transactron/lib/dependencies.py
  transactron/tracing.py
  transactron/utils/dependencies.py
Labels: infrastructure

#666 Restore TransactionManager's debug signals
  transactron/core/manager.py
Labels: bug

#667 Fix fetcher throughput
  coreblocks/frontend/fetch/fetch.py
Labels: optimization, benchmark

#671 Sort benchmarks
  scripts/run_benchmarks.py
Labels: infrastructure, benchmark

#674 Stall fetch on JALR instruction
  coreblocks/frontend/fetch/fetch.py
Labels: optimization, benchmark

#673 Measure trap latency
  coreblocks/backend/retirement.py
Labels: enhancement, benchmark

#670 Fix benchmark workflow
  .github/workflows/benchmark.yml
  .github/workflows/publish_comment.yml
  ci/print_benchmark_summary.py
Labels: bug, infrastructure

#663 Add custom combiners
  test/transactron/test_methods.py
  transactron/core/manager.py
  transactron/core/method.py
Labels: enhancement, transactions

#683 Use 'assign' in testbenchio
  test/backend/test_retirement.py
  test/func_blocks/fu/common/test_rs.py
  test/peripherals/test_wishbone.py
  test/transactron/test_adapter.py
  transactron/testing/functions.py
  transactron/testing/testbenchio.py
Labels: tests, refactor

#680 Remove relation graph in Transactron
  test/transactron/test_branches.py
  transactron/core/manager.py
  transactron/profiler.py
Labels: transactions

#661 Support for UnionLayout in assign and other changes
  test/transactron/test_assign.py
  transactron/utils/assign.py
Labels: enhancement

#688 Dependency caching in DependencyManager
  coreblocks/core.py
  coreblocks/func_blocks/interface/func_blocks_unifier.py
  transactron/utils/dependencies.py
Labels: enhancement

#684 Intuitive condition statement
  coreblocks/backend/retirement.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/priv.py
  transactron/lib/simultaneous.py
  transactron/lib/transformers.py
Labels: transactions

#687 Use DependencyContext in Coreblocks
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/priv/csr/csr_register.py
  coreblocks/priv/traps/exception.py
  coreblocks/priv/traps/interrupt_controller.py
  coreblocks/scheduler/scheduler.py
  test/backend/test_retirement.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  test/scheduler/test_scheduler.py
Labels: refactor

#689 Fix after #687
  scripts/synthesize.py
Labels: bug

#691 Implement WFI
  coreblocks/frontend/decoder/optypes.py
  coreblocks/func_blocks/fu/priv.py
  test/asm/wfi_int.asm
  test/asm/wfi_no_int.asm
  test/test_core.py
Labels: enhancement
