Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-05, with the labels that each got.

#682 Move common code to a new dir
  coreblocks/arch/__init__.py
  coreblocks/arch/isa.py
  coreblocks/arch/isa_consts.py
  coreblocks/arch/optypes.py
  coreblocks/backend/retirement.py
  coreblocks/frontend/decoder/__init__.py
  coreblocks/frontend/decoder/decode_stage.py
  coreblocks/frontend/decoder/instr_decoder.py
  coreblocks/frontend/decoder/instr_description.py
  coreblocks/frontend/decoder/rvc.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/alu.py
  coreblocks/func_blocks/fu/common/fu_decoder.py
  coreblocks/func_blocks/fu/common/rs.py
  coreblocks/func_blocks/fu/common/rs_func_block.py
  coreblocks/func_blocks/fu/div_unit.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/mul_unit.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/func_blocks/fu/shift_unit.py
  coreblocks/func_blocks/fu/zbc.py
  coreblocks/func_blocks/fu/zbs.py
  coreblocks/interface/layouts.py
  coreblocks/params/__init__.py
  coreblocks/params/configurations.py
  coreblocks/params/fu_params.py
  coreblocks/params/genparams.py
  coreblocks/params/instr.py
  coreblocks/priv/traps/exception.py
  coreblocks/scheduler/scheduler.py
  test/common/test_isa.py
  test/frontend/test_decode_stage.py
  test/frontend/test_fetch.py
  test/frontend/test_instr_decoder.py
  test/frontend/test_rvc.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/common/test_rs.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/fu/test_alu.py
  test/func_blocks/fu/test_div_unit.py
  test/func_blocks/fu/test_exception_unit.py
  test/func_blocks/fu/test_fu_decoder.py
  test/func_blocks/fu/test_jb_unit.py
  test/func_blocks/fu/test_mul_unit.py
  test/func_blocks/fu/test_shift_unit.py
  test/func_blocks/fu/test_zbc.py
  test/func_blocks/fu/test_zbs.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  test/params/test_configurations.py
  test/params/test_instr.py
  test/priv/traps/test_exception.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/test_core.py
Labels: refactor

#685 Branch Prediction Checker
  coreblocks/arch/optypes.py
  coreblocks/frontend/__init__.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/frontend/frontend_params.py
  coreblocks/interface/layouts.py
  coreblocks/params/genparams.py
  test/frontend/test_fetch.py
Labels: enhancement, microarch

#679 Mocking validate_arguments
  test/transactron/testing/test_validate_arguments.py
  transactron/lib/adapters.py
  transactron/testing/testbenchio.py
Labels: transactions, tests

#696 Move LSURequester
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/lsu_requester.py
  coreblocks/params/genparams.py
  test/func_blocks/lsu/test_dummylsu.py
Labels: refactor

#694 Fix double logger adding - master
  test/transactron/testing/test_log.py
  transactron/testing/infrastructure.py
  transactron/testing/logging.py
Labels: bug

#701 CSR addresses
  coreblocks/priv/csr/csr_address.py
  coreblocks/priv/csr/csr_instances.py
Labels: enhancement

#698 Create CoreFrontend module
  coreblocks/core.py
  coreblocks/frontend/frontend.py
  test/test_core.py
Labels: refactor

#681 Fix fetch resume
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/layouts.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  test/frontend/test_fetch.py
  transactron/core/method.py
Labels: bug

#699 Move CoreCounter behind the frontend
  coreblocks/core.py
  coreblocks/frontend/frontend.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  test/test_core.py
Labels: optimization

#573 Port ContentAddressableMemory from #395
  .gitignore
  requirements-dev.txt
  test/frontend/test_decode_stage.py
  test/frontend/test_fetch.py
  test/func_blocks/fu/functional_common.py
  test/transactron/test_transactron_lib_storage.py
  test/transactron/utils/test_amaranth_ext.py
  transactron/lib/storage.py
  transactron/testing/__init__.py
  transactron/testing/infrastructure.py
  transactron/testing/input_generation.py
  transactron/utils/amaranth_ext/elaboratables.py
  transactron/utils/transactron_helpers.py
Labels: enhancement

#704 Add new M-mode CSRs
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/priv/csr/csr_instances.py
  test/asm/csr_mmode.asm
  test/test_core.py
Labels: enhancement

#654 Internal Interrupt Controller
  .gitignore
  coreblocks/arch/__init__.py
  coreblocks/arch/csr_address.py
  coreblocks/arch/isa_consts.py
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/interface/layouts.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/priv/csr/aliased.py
  coreblocks/priv/csr/csr_instances.py
  coreblocks/priv/traps/interrupt_controller.py
  scripts/run_tests.py
  test/asm/interrupt.asm
  test/asm/wfi_int.asm
  test/backend/test_retirement.py
  test/frontend/test_fetch.py
  test/test_core.py
Labels: enhancement
