Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-02, with the labels that each got.

#576 Update amaranth version to the v0.4.x head
  requirements.txt
Labels: enhancement

#578 Refactor & improvements of regression scripts
  scripts/run_benchmarks.py
  scripts/run_signature.py
  scripts/run_tests.py
  test/regression/benchmark.py
  test/regression/cocotb.py
  test/regression/cocotb/benchmark.Makefile
  test/regression/cocotb/signature.Makefile
  test/regression/cocotb/test.Makefile
  test/regression/common.py
  test/regression/pysim.py
  test/regression/test.py
  transactron/core.py
Labels: infrastructure, refactor

#543 Icache code split
  coreblocks/cache/__init__.py
  coreblocks/cache/icache.py
  coreblocks/cache/iface.py
  coreblocks/cache/refiller.py
  coreblocks/core.py
  coreblocks/frontend/fetch.py
  test/cache/__init__.py
  test/cache/test_icache.py
  test/frontend/test_fetch.py
Labels: refactor

#357 Migration to amaranth.lib.data
  constants/ecp5_platforms.py
  coreblocks/fu/fu_decoder.py
  coreblocks/fu/mul_unit.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/layouts.py
  coreblocks/peripherals/axi_lite.py
  coreblocks/peripherals/bus_adapter.py
  coreblocks/peripherals/wishbone.py
  coreblocks/scheduler/scheduler.py
  coreblocks/scheduler/wakeup_select.py
  coreblocks/stages/retirement.py
  coreblocks/structs_common/csr.py
  coreblocks/structs_common/rob.py
  coreblocks/structs_common/rs.py
  stubs/amaranth/hdl/ast.pyi
  test/common/functions.py
  test/fu/test_jb_unit.py
  test/gtkw_extension.py
  test/scheduler/test_wakeup_select.py
  test/structs_common/test_rs.py
  test/transactions/test_assign.py
  test/transactions/test_methods.py
  test/transactions/test_simultaneous.py
  test/transactions/test_transaction_lib.py
  transactron/core.py
  transactron/lib/adapters.py
  transactron/lib/buttons.py
  transactron/lib/connectors.py
  transactron/lib/fifo.py
  transactron/lib/reqres.py
  transactron/lib/storage.py
  transactron/lib/transformers.py
  transactron/utils/_typing.py
  transactron/utils/assign.py
  transactron/utils/data_repr.py
  transactron/utils/transactron_helpers.py
Labels: refactor

#569 Move `tests/common` to `transactron`
  test/cache/test_icache.py
  test/frontend/test_decode_stage.py
  test/frontend/test_fetch.py
  test/frontend/test_instr_decoder.py
  test/frontend/test_rvc.py
  test/fu/functional_common.py
  test/fu/test_fu_decoder.py
  test/fu/test_unsigned_mul_unit.py
  test/lsu/test_dummylsu.py
  test/lsu/test_pma.py
  test/peripherals/test_axi_lite.py
  test/peripherals/test_wishbone.py
  test/regression/pysim.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
  test/stages/test_backend.py
  test/stages/test_retirement.py
  test/structs_common/test_csr.py
  test/structs_common/test_exception.py
  test/structs_common/test_rat.py
  test/structs_common/test_reorder_buffer.py
  test/structs_common/test_rs.py
  test/test_core.py
  test/transactions/test_adapter.py
  test/transactions/test_branches.py
  test/transactions/test_methods.py
  test/transactions/test_simultaneous.py
  test/transactions/test_transaction_lib.py
  test/transactions/test_transactions.py
  test/transactron/testing/__init__.py
  test/transactron/testing/test_infrastructure.py
  test/utils/test_fifo.py
  test/utils/test_onehotswitch.py
  test/utils/test_utils.py
  transactron/testing/__init__.py
  transactron/testing/functions.py
  transactron/testing/gtkw_extension.py
  transactron/testing/infrastructure.py
  transactron/testing/profiler.py
  transactron/testing/sugar.py
  transactron/testing/testbenchio.py
Labels: tests, refactor

#581 Use DependencyManager as the global object
  scripts/core_graph.py
  test/transactions/test_transactions.py
  transactron/__init__.py
  transactron/core.py
  transactron/testing/infrastructure.py
  transactron/utils/dependencies.py
Labels: enhancement

#538 Assertions in hardware
  test/frontend/test_instr_decoder.py
  test/transactions/test_branches.py
  test/transactions/test_methods.py
  test/transactions/test_transactions.py
  test/transactron/__init__.py
  test/transactron/testing/test_assertion.py
  transactron/core.py
  transactron/testing/__init__.py
  transactron/testing/assertion.py
  transactron/testing/infrastructure.py
  transactron/testing/profiler.py
  transactron/utils/__init__.py
  transactron/utils/_typing.py
  transactron/utils/assertion.py
Labels: enhancement, tests

#580 Hardware Metrics
  test/transactron/test_metrics.py
  transactron/lib/__init__.py
  transactron/lib/metrics.py
  transactron/utils/dependencies.py
Labels: enhancement

#593 Fix Zbb instructions en/decoding
  coreblocks/frontend/instr_description.py
  coreblocks/fu/alu.py
  coreblocks/fu/shift_unit.py
  coreblocks/params/optypes.py
  test/frontend/test_instr_decoder.py
  test/fu/test_alu.py
  test/fu/test_shift_unit.py
Labels: bug
