Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-12, with the labels that each got.

#765 Synchronous register file using MemoryBank
  coreblocks/core.py
  coreblocks/core_structs/rf.py
  coreblocks/scheduler/scheduler.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/test_core.py
Labels: optimization, benchmark

#766 Use bit vector allocator for free registers
  coreblocks/core.py
  coreblocks/params/genparams.py
Labels: refactor, benchmark

#741 LZA (Leading zeros anticipation)
  coreblocks/func_blocks/fu/fpu/lza.py
  test/func_blocks/fu/fpu/test_lza.py
Labels: enhancement

#770 De-Wishbonized tests
  test/cache/test_icache.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  test/peripherals/bus_mock.py
Labels: refactor
