Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-09, with the labels that each got.

#731 Add `def_methods`
  test/transactron/test_methods.py
  transactron/core/sugar.py
Labels: enhancement, transactions

#730 Clean up `MemoryBank`
  test/transactron/lib/test_transaction_lib.py
  transactron/lib/storage.py
Labels: refactor

#723 Support top-level signals in TransactionComponent
  transactron/core/manager.py
Labels: transactions, benchmark
