Repository kuznia-rdzeni/coreblocks, pull requests merged in 2024-03, with the labels that each got.

#594 Enable tests for extensions in riscv-arch-test
  test/external/riscof/coreblocks/coreblocks_isa.yaml
  test/external/riscof/coreblocks/riscof_coreblocks.py
  test/external/riscof/spike_simple/riscof_spike_simple.py
  test/external/riscof/spike_simple/spike_simple_isa.yaml
Labels: infrastructure, tests

#577 A step towards amaranth `v0.5.0`
  constants/ecp5_platforms.py
  coreblocks/cache/icache.py
  coreblocks/cache/refiller.py
  coreblocks/lsu/dummyLsu.py
  coreblocks/params/genparams.py
  coreblocks/params/instr.py
  requirements.txt
  stubs/amaranth/_unused.pyi
  stubs/amaranth/build/res.pyi
  stubs/amaranth/hdl/__init__.pyi
  stubs/amaranth/hdl/_ast.pyi
  stubs/amaranth/hdl/_cd.pyi
  stubs/amaranth/hdl/_dsl.pyi
  stubs/amaranth/hdl/_ir.pyi
  stubs/amaranth/hdl/_mem.pyi
  stubs/amaranth/hdl/_xfrm.pyi
  stubs/amaranth/lib/data.pyi
  stubs/amaranth/lib/enum.pyi
  stubs/amaranth/lib/fifo.pyi
  stubs/amaranth/sim/core.pyi
  stubs/amaranth/utils.pyi
  stubs/amaranth/vendor/__init__.pyi
  stubs/amaranth/vendor/_lattice_ecp5.pyi
  stubs/amaranth/vendor/_lattice_ice40.pyi
  test/cache/test_icache.py
  test/regression/pysim.py
  test/transactions/test_assign.py
  transactron/core.py
  transactron/graph.py
  transactron/lib/connectors.py
  transactron/lib/reqres.py
  transactron/testing/functions.py
  transactron/tracing.py
  transactron/utils/_typing.py
  transactron/utils/amaranth_ext/elaboratables.py
  transactron/utils/amaranth_ext/functions.py
  transactron/utils/assign.py
  transactron/utils/gen.py
Labels: enhancement

#590 Assertions in cocotb
  stubs/amaranth/_toolchain/yosys.pyi
  stubs/amaranth/back/__init__.pyi
  stubs/amaranth/back/verilog.pyi
  test/regression/cocotb.py
  test/transactron/testing/test_assertion.py
  transactron/testing/assertion.py
  transactron/utils/assertion.py
  transactron/utils/gen.py
Labels: enhancement, tests

#554 Add pytest - step 2
  .github/workflows/main.yml
  .gitignore
  pytest.ini
  requirements-dev.txt
  scripts/check_test_results.py
  scripts/run_tests.py
  test/conftest.py
  test/regression/cocotb/test_entrypoint.py
  test/regression/conftest.py
  test/regression/test.py
  test/regression/test_regression.py
Labels: infrastructure

#604 Fix the pysim regression
  test/regression/test_regression.py
Labels: bug

#608 Add CI runs for #604
  .github/workflows/main.yml
Labels: infrastructure

#615 Add B extension support to the toolchain Dockerfile
  docker/riscv-toolchain.Dockerfile
Labels: infrastructure

#616 Enable division and bit manipulation extensions in benchmarks
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
  test/external/embench/board_config/coreblocks-sim/board.cfg
Labels: infrastructure

#607 Fix profiles on newer yosys version
  test/regression/cocotb.py
  transactron/utils/gen.py
Labels: bug, infrastructure

#609 Migration to amaranth.lib.wiring
  coreblocks/core.py
  coreblocks/peripherals/axi_lite.py
  coreblocks/peripherals/wishbone.py
  scripts/gen_verilog.py
  scripts/synthesize.py
  stubs/amaranth/lib/wiring.pyi
  test/peripherals/test_axi_lite.py
  test/peripherals/test_wishbone.py
  test/regression/pysim.py
  test/test_core.py
  transactron/utils/_typing.py
Labels: refactor

#612 Destroy all records
  coreblocks/cache/icache.py
  coreblocks/fu/div_unit.py
  coreblocks/fu/fu_decoder.py
  coreblocks/lsu/pma.py
  coreblocks/params/layouts.py
  coreblocks/structs_common/rf.py
  stubs/amaranth/hdl/_ast.pyi
  test/transactions/test_assign.py
  transactron/lib/storage.py
  transactron/utils/_typing.py
  transactron/utils/assign.py
Labels: refactor

#618 Optimize submodule downloads in CI
  .github/workflows/main.yml
Labels: infrastructure

#617 Split transactron core
  coreblocks/structs_common/rs.py
  scripts/core_graph.py
  test/regression/pysim.py
  test/transactions/test_branches.py
  test/transactions/test_transaction_lib.py
  test/transactions/test_transactions.py
  transactron/__init__.py
  transactron/core.py
  transactron/core/__init__.py
  transactron/core/keys.py
  transactron/core/manager.py
  transactron/core/method.py
  transactron/core/schedulers.py
  transactron/core/sugar.py
  transactron/core/tmodule.py
  transactron/core/transaction.py
  transactron/core/transaction_base.py
  transactron/lib/adapters.py
  transactron/lib/buttons.py
  transactron/lib/connectors.py
  transactron/lib/reqres.py
  transactron/lib/transformers.py
  transactron/profiler.py
  transactron/testing/infrastructure.py
  transactron/testing/profiler.py
  transactron/testing/testbenchio.py
  transactron/utils/_typing.py
  transactron/utils/gen.py
Labels: refactor

#622 Update GH actions for Node 20
  .github/workflows/benchmark.yml
  .github/workflows/deploy_gh_pages.yml
  .github/workflows/main.yml
Labels: infrastructure

#623 Allow parallel compilation of the verilated model
  test/regression/cocotb/benchmark.Makefile
  test/regression/cocotb/signature.Makefile
  test/regression/cocotb/test.Makefile
Labels: infrastructure

#621 Add selecting network circuit
  test/transactron/test_connectors.py
  transactron/lib/connectors.py
Labels: enhancement

#624 Support for superscalarity in the instruction cache
  coreblocks/cache/icache.py
  coreblocks/cache/iface.py
  coreblocks/cache/refiller.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/interface/layouts.py
  coreblocks/params/configurations.py
  coreblocks/params/genparams.py
  coreblocks/params/icache_params.py
  test/cache/test_icache.py
  test/frontend/test_fetch.py
  test/frontend/test_rvc.py
  test/regression/memory.py
  test/test_core.py
Labels: enhancement
