Repository kuznia-rdzeni/coreblocks, pull requests merged in 2025-01, with the labels that each got.

#776 Transactron refactor
  coreblocks/backend/retirement.py
  coreblocks/core_structs/rob.py
  coreblocks/func_blocks/fu/common/rs.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/priv/csr/csr_register.py
  coreblocks/priv/traps/exception.py
  requirements.txt
  test/backend/test_annoucement.py
  test/backend/test_retirement.py
  test/cache/test_icache.py
  test/frontend/test_fetch.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  test/peripherals/bus_mock.py
  test/priv/traps/test_exception.py
  test/scheduler/test_rs_selection.py
  test/scheduler/test_scheduler.py
  test/scheduler/test_wakeup_select.py
Labels: refactor, dependencies

#780 Older Ubuntu in workflows
  .github/workflows/benchmark.yml
  .github/workflows/main.yml
Labels: infrastructure, benchmark

#779 Implement Zaamo - atomic memory operations extension
  coreblocks/arch/isa.py
  coreblocks/arch/isa_consts.py
  coreblocks/arch/optypes.py
  coreblocks/frontend/decoder/instr_decoder.py
  coreblocks/frontend/decoder/instr_description.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/lsu_atomic_wrapper.py
  coreblocks/params/configurations.py
  test/common/test_isa.py
  test/frontend/test_instr_decoder.py
  test/func_blocks/lsu/test_lsu_atomic_wrapper.py
  test/params/test_configurations.py
Labels: enhancement

#791 Update Transactron
  coreblocks/core_structs/rf.py
  requirements.txt
  test/regression/pysim.py
Labels: dependencies

#784 Make FU params more consistent
  coreblocks/func_blocks/fu/alu.py
  coreblocks/func_blocks/fu/div_unit.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/lsu_atomic_wrapper.py
  coreblocks/func_blocks/fu/mul_unit.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/func_blocks/fu/shift_unit.py
  coreblocks/func_blocks/fu/zbc.py
  coreblocks/func_blocks/fu/zbs.py
  coreblocks/params/fu_params.py
  scripts/synthesize.py
Labels: refactor

#785 Use WideFifo in fetch
  coreblocks/frontend/fetch/fetch.py
Labels: refactor, benchmark

#792 Push result from FUs
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/alu.py
  coreblocks/func_blocks/fu/common/rs_func_block.py
  coreblocks/func_blocks/fu/div_unit.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/lsu_atomic_wrapper.py
  coreblocks/func_blocks/fu/mul_unit.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/func_blocks/fu/shift_unit.py
  coreblocks/func_blocks/fu/zbc.py
  coreblocks/func_blocks/fu/zbs.py
  coreblocks/func_blocks/interface/func_protocols.py
  coreblocks/interface/layouts.py
  coreblocks/params/fu_params.py
  scripts/synthesize.py
  test/backend/test_annoucement.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/fu/test_jb_unit.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_lsu_atomic_wrapper.py
  test/func_blocks/lsu/test_pma.py
Labels: refactor, benchmark

#797 Add --reset-pc option to scripts/gen_verilog
  scripts/gen_verilog.py
Labels: enhancement
