Repository kuznia-rdzeni/coreblocks, pull requests merged in 2025-02, with the labels that each got.

#801 Remove transactron from pyrightconfig
  pyrightconfig.json
Labels: bug

#782 Implement Zalrsc - load-reserved/store-conditional instructions extension
  coreblocks/arch/isa.py
  coreblocks/arch/isa_consts.py
  coreblocks/arch/optypes.py
  coreblocks/frontend/decoder/instr_description.py
  coreblocks/func_blocks/fu/lsu/lsu_atomic_wrapper.py
  test/common/test_isa.py
  test/frontend/test_instr_decoder.py
  test/func_blocks/lsu/test_lsu_atomic_wrapper.py
  test/params/test_configurations.py
Labels: enhancement

#802 Update transactron and pyright
  constants/ecp5_platforms.py
  coreblocks/func_blocks/fu/common/fu_decoder.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/lsu/lsu_atomic_wrapper.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/func_blocks/fu/zbc.py
  coreblocks/interface/layouts.py
  coreblocks/peripherals/wishbone.py
  requirements-dev.txt
  requirements.txt
  test/frontend/test_instr_decoder.py
  test/func_blocks/fu/test_fu_decoder.py
  test/regression/cocotb.py
  test/regression/cocotb/signature_entrypoint.py
  test/regression/signature.py
Labels: dependencies, benchmark

#796 Add the stall controller
  coreblocks/core.py
  coreblocks/frontend/fetch/fetch.py
  coreblocks/frontend/frontend.py
  coreblocks/frontend/stall_controller.py
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/keys.py
  coreblocks/interface/layouts.py
  scripts/core_graph.py
  test/frontend/test_fetch.py
  test/func_blocks/csr/test_csr.py
Labels: enhancement, refactor

#786 Remove constructor passed methods
  coreblocks/backend/annoucement.py
  coreblocks/backend/retirement.py
  coreblocks/core.py
  coreblocks/frontend/decoder/decode_stage.py
  coreblocks/frontend/frontend.py
  coreblocks/func_blocks/fu/common/rs_func_block.py
  coreblocks/scheduler/wakeup_select.py
  test/backend/test_annoucement.py
  test/backend/test_retirement.py
  test/frontend/test_decode_stage.py
  test/scheduler/test_wakeup_select.py
Labels: refactor

#800 Remove conflict between FUs reporting exceptions
  coreblocks/func_blocks/csr/csr.py
  coreblocks/func_blocks/fu/exception.py
  coreblocks/func_blocks/fu/jumpbranch.py
  coreblocks/func_blocks/fu/lsu/dummyLsu.py
  coreblocks/func_blocks/fu/priv.py
  coreblocks/interface/keys.py
  coreblocks/priv/traps/exception.py
  test/func_blocks/csr/test_csr.py
  test/func_blocks/fu/functional_common.py
  test/func_blocks/lsu/test_dummylsu.py
  test/func_blocks/lsu/test_pma.py
  test/priv/traps/test_exception.py
Labels: optimization
