Repository kuznia-rdzeni/coreblocks, pull requests merged in 2025-03, with the labels that each got.

#768 Far path for fpu adder/subtractor
  coreblocks/func_blocks/fu/fpu/far_path.py
  coreblocks/func_blocks/fu/fpu/fpu_common.py
  test/func_blocks/fu/fpu/test_far_path.py
Labels: enhancement

#807 Fix typo in coreblocks/priv/traps/interrupt_controller.py
  coreblocks/priv/traps/interrupt_controller.py
Labels: documentation

#804 Simplify JumpBranchFn
  coreblocks/func_blocks/fu/jumpbranch.py
  test/func_blocks/fu/test_jb_unit.py
Labels: refactor

#811 Change custom machine cause reg values in isa_consts.py
  coreblocks/arch/isa_consts.py
Labels: bug
